apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sock-shop
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: istio-system
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: infrastructure
  path: ./apps
  prune: true
  validation: client
