apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: notification-alert
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
  - kind: Kustomization
    name: '*'
  - kind: GitRepository
    name: '*'
  - kind: ImageRepository
    name: "*"
  - kind: ImagePolicy
    name: "*"
  - kind: ImageUpdateAutomation
    name: "*"
  providerRef:
    name: notification-provider