apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: notification-provider
  namespace: flux-system
spec:
  channel: flux-notifications
  secretRef:
    name: discord-url
  type: discord
  username: flux-bot

