apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: orders
  namespace: sock-shop
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 600
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: orders
  service:
    # container port
    port: 80
    trafficPolicy:
      tls:
        # use ISTIO_MUTUAL when mTLS is enabled
        mode: DISABLE
  analysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 25
    # precentage before complete rollout
    maxWeight: 50
    # 10% steps
    stepWeight: 10
    # promotion increment step (default 100)
    stepWeightPromotion: 100

    alerts:
      - name: "on-call Discord"
        severity: info
        providerRef:
          name: on-call
          namespace: flux-system
    #Built in Flagger metrics
#    metrics:
#      - name: request-success-rate
#        templateRef:
#          name: request-success-rate
#          namespace: istio-system
#        interval: 1m
#        thresholdRange:
#          min: 90
#      - name: request-duration
#        templateRef:
#          name: request-duration
#          namespace: istio-system
#        interval: 1m
#        thresholdRange:
#          max: 1000
  skipAnalysis: false #svc does not get traffic since other services like carts are not available
