apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    name: orders
    app: orders
  namespace: sock-shop
spec:
  selector:
    matchLabels:
      name: orders
      app: orders
  template:
    metadata:
      labels:
        name: orders
        app: orders
    spec:
      containers:
        - name: orders

          image: europe-west3-docker.pkg.dev/cnpe-blue/sockshop/orders:1.0.1

          env:
            - name: JAVA_OPTS
              value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 300Mi
          ports:
            - containerPort: 80
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
